name: CI

on:
  push:
    branches: [ main ]

jobs:
  secret_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: channelbeta/secret-scan@2.1.0
        with:
          exclude_path: './path_exclude/exclude.txt'

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Maven
        run: |
          sudo apt install maven
          mvn clean package
      - name: Build docker-compose
        run: docker-compose -f docker-compose.yml up --build -d
  
  sca:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/ApplicationInspector-Action@v1
      - uses: actions/upload-artifact@v2
        with:
          name: AppInspectorResults
          path: AppInspectorResults.json            
  
  sast:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install --production=false
      - name: Scan code
        uses: vtex/action-sonarqube@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          host: ${{ secrets.SQHost }} # Variable set in the Github Secrets
          token: ${{ secrets.SQToken }} # Variable set in the Github Secrets
    
  #codeql:
    #runs-on: ubuntu-latest
    #steps:      
     # - uses: actions/checkout@v2
      
      #- name: Initialize CodeQL
       # uses: github/codeql-action/init@v1
        #with:
         # languages: java
          
      #- name: Autobuild
       # uses: github/codeql-action/autobuild@v1

     # - name: Perform CodeQL Analysis
      #  uses: github/codeql-action/analyze@v1
      #- uses: actions/upload-artifact@v2
       # with:
        #  name: /home/runner/work/_temp/codeql_databases/java.zip
         # path: java.zip         
        
  unit_testing:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#to put commands to build application, install relevant packages for testing and run testings below
      - run: echo "test"

      - name: Run Maven
        run: |
          sudo apt install maven
          mvn clean package
      
      - name: Build Image for testing
        run: docker-compose -f docker-compose.yml up --build -d

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
           python-version: "3.6"

      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install -r test/requirement.txt
           
      - name: Run functional tests
        run: |
           python test/landing_page_test.py
           python test/functional_test_login.py
      
  image_scan:
    needs: [sca, sast, unit_testing]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo docker pull tomcat
      - uses: hands-lab/dockle-action@v1
        with:
          image: tomcat
          
  deployment: 
    needs: image_scan
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: echo "test"
#########################put commands for deployment############################

  dast:
#    needs: deployment
#remove above line one pipeline all green
    runs-on: ubuntu-latest
    env:
      ip_addr: $(python extra/get_ip.py)
    steps:
      - uses: actions/checkout@v2
      - name: Run Maven
        run: |
          sudo apt install maven
          mvn clean package
      
      - name: Build Image for testing
        run: docker-compose -f docker-compose.yml up --build -d

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
           python-version: "3.6"

      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install -r test/requirement.txt
           
      - name: ZAP Scan
        run: docker run -t owasp/zap2docker-stable zap-baseline.py -t http://127.0.0.1:8080/CRMMVC/
        #uses: zaproxy/action-baseline@v0.6.1
        #with:
         #token: ${{ secrets.GITHUB_TOKEN }}
         #docker_name: 'owasp/zap2docker-stable'
         #target: 'http://127.0.0.1:8080/CRMMVC/'
         #cmd_options: '-a'   
  
